"""empty message

Revision ID: 133ac2675013
Revises: 7b6bc71d7414
Create Date: 2019-03-04 01:48:48.547482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133ac2675013'
down_revision = '7b6bc71d7414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
